import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { Heading, Flex, Text } from '@chakra-ui/react';
import headImage from "../../public/images/peggy-paulson-brittany.jpeg";
import HeaderBar from './HeaderBar.js';
import Grid from './Grid.js';
import AboutSection from './AboutSection.js';
import Location from './Location.js';
import MidBody from './MidBody.js';
import BrickLogo from './BrickLogo.js';
import Footer from './Footer.js';
import Form from './Form.js';

export default function Home() {
  return (
    <>
      <Head>
        <title>On Point!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/gkk1jyc.css"></link>
        <link rel="stylesheet" href="https://use.typekit.net/vjj0zuy.css"></link>
        <link rel="stylesheet" href="https://use.typekit.net/vjj0zuy.css"></link>
        <link rel="stylesheet" href="https://use.typekit.net/eji5tuw.css"></link>
        
      </Head>
      <BrickLogo />
        <HeaderBar />
          <AboutSection />
          <Location />
          <MidBody />
          <Grid />
          <Form />
        <Footer />
    </>
  )
}
